project_id = "prptyyuvwyusfucroitd"

[functions.chat]
verify_jwt = false

[functions.classify-lead]
verify_jwt = false

[functions.save-whatsapp-message]
verify_jwt = false

[functions.update-ai-config]
verify_jwt = false

[functions.trigger-agent-config]
verify_jwt = false

[functions.consultar-produtos]
verify_jwt = false

[functions.update-conversation-status]
verify_jwt = false

[functions.update-lead-status]
verify_jwt = false

[functions.sync-chat]
verify_jwt = false

[functions.consultar-config-agente]
verify_jwt = false
